### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by loperacomdata** [anildias/issue_notifier#5]
in redmine 4.1.1
[redmine@SRV redmine-4.1.1]$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/opt/redmine/redmine-4.1.1/plugins/issue_notifier/init.rb:48:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/redmine-4.1.1/lib/redmine/plugin.rb:181:in `block in load'
/opt/redmine/redmine-4.1.1/lib/redmine/plugin.rb:172:in `each'
/opt/redmine/redmine-4.1.1/lib/redmine/plugin.rb:172:in `load'
/opt/redmine/redmine-4.1.1/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.1.1/config/environment.rb:16:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `<main>'

**Comment by iBelverus** [comment]
It was my first issue last time.
1. Use redmine env first (<install dir>/use_redmine)
2. Install redis server (I recommend redis 4.0.14 - it works for me)
2. Install gems: bundle install (it may require additional params, so just follow recommendations)
3. Make changes described in my issues here
4. Perform the migration
5. As for sidekiq, read the official docs of how to run Sidekiq 6.0.7 and higher in the background (I set up systemd service)
